name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CarbonSmasher/packtest_runner@b04938db10856d5973a20ba7f50c2783c0837c0b
        with:
          packs: example-datapack.zip
