name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CarbonSmasher/packtest_runner@c80527be561533444625699edc975a618ea44c31
        with:
          packs: example-datapack.zip
