name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CarbonSmasher/packtest_runner@73c6f670b1a7cc2610c63c77f0d0912f87e0ddb2
        with:
          packs: example-datapack.zip
