name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CarbonSmasher/packtest_runner@e2cab04a758a802a6ebcee979fe40fb0140df3de
        with:
          packs: example-datapack.zip
