name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CarbonSmasher/packtest_runner@af9f3efb5a9380a2d076dbdfaacc3d0fa8431bb1
        with:
          packs: example-datapack.zip
