name: Run tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CarbonSmasher/packtest_runner@ddbe30797f388a8efe89922c68f40d98668ed95a
        with:
          packs: example-datapack.zip
